//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.excilys.capicsoubank.activity;

import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.KeyEvent;
import android.view.Menu;
import android.view.MenuInflater;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.EditText;
import android.widget.Spinner;
import com.excilys.capicsoubanktabletannotation.R.id;
import com.excilys.capicsoubanktabletannotation.R.layout;
import com.googlecode.androidannotations.api.SdkVersionHelper;

public final class DisplayTransferActivity_
    extends DisplayTransferActivity
{


    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.activity_display_transfer);
    }

    private void init_(Bundle savedInstanceState) {
    }

    private void afterSetContentView_() {
        transferError = ((View) findViewById(id.transferError));
        sourceAccount = ((Spinner) findViewById(id.sourceAccount));
        destinationAccount = ((Spinner) findViewById(id.destinationAccount));
        transferForm = ((View) findViewById(id.transferForm));
        transferFinished = ((View) findViewById(id.transferFinished));
        amountEdit = ((EditText) findViewById(id.amount));
        {
            View view = findViewById(id.buttonTransfer);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        DisplayTransferActivity_.this.buttonTransfer();
                    }

                }
                );
            }
        }
        getAccounts();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

    public static DisplayTransferActivity_.IntentBuilder_ intent(Context context) {
        return new DisplayTransferActivity_.IntentBuilder_(context);
    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        MenuInflater menuInflater = getMenuInflater();
        menuInflater.inflate(com.excilys.capicsoubanktabletannotation.R.menu.menu, menu);
        return super.onCreateOptionsMenu(menu);
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, DisplayTransferActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public DisplayTransferActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

    }

}
